Embeds bug: Revert changes that required both embeds to have content in order to save
ordercloud-api/angular-cms-components pull request #75
Opened 2021-04-02 16:01 UTC by ricocynthia

New bug was introduction with the latest release. If you added content in the header embed, you were not able to save the page without adding content in the footer embed (vice-versa). These changes allow users to save their changes, even if they only have content in one of the embeds text box.

2021-04-02 17:03 UTC, kwahn20 requested changes
I think we should add in some more validation to ensure the script tags are valid. Currently, I can just write plain text such as "script" and it passes the validation and I can save the changes. Another thing we may want to add in is some validation to make sure that a closing script tag is the final part of each embed section

2021-04-05 15:14 UTC, ricocynthia commented
@kwahn20 alrighty just pushed up the final changes for your suggestions. I found this cool repo that someone built that checks if tags are closed: https://github.com/coopersita/closing-tag-checker. This helped me write out the `checkForClosingTags(content: string, embed: string)` method

 when reviewing, please make sure to test with non self closing tags as well 😀

2021-04-05 16:10 UTC, kwahn20 approved these changes

2021-04-05 16:11 UTC, kwahn20 approved these changes

2021-04-05 16:11 UTC, merged